# SPDX-License-Identifier: MIT
#
# Copyright (c) 2024 Berachain Foundation
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

name: release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'release/*'

env:
  REPO_NAME: beacon-kit
  IMAGE_NAME: beacon-kit
  
jobs:
  extract-version:
    name: extract version
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT
        id: extract_version
    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}

  build-linux:
    runs-on: ubuntu-latest
    needs: extract-version
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [linux]

    name: beacond-${{ matrix.targetos }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.22"
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      # Build and capture an artifact
      - name: Build beacond
        run: |
          make build-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}
          tar -czvf beacond-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}.tar.gz -C build/bin .

      # Uploads binaries
      - uses: actions/upload-artifact@v3
        with:
          name: beacond-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}.tar.gz
          path: beacond-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}.tar.gz

  build-mac:
    runs-on: macos-latest
    needs: extract-version
    strategy:
      matrix:
        arch: [arm64]
        targetos: [darwin]

    name: beacond-${{ matrix.targetos }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.22"
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
          CGO_CFLAGS: "-O -D__BLST_PORTABLE__"
          CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"

      # Build and capture an artifact
      - name: Build beacond
        run: |
          make build-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}
          tar -czvf beacond-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}.tar.gz -C build/bin .

      # Uploads binaries
      - uses: actions/upload-artifact@v3
        with:
          name: beacond-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}.tar.gz
          path: beacond-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.targetos }}-${{ matrix.arch }}.tar.gz

  draft-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac, extract-version]
    env:
      VERSION: ${{ needs.extract-version.outputs.VERSION }}
    permissions:
      # Required to post the release
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This is necessary for generating the changelog.
      # It has to come before "Download Artifacts" or else it deletes the artifacts.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Generate full changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 ${{ env.VERSION }}^)..${{ env.VERSION }})" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Draft Release
        uses: softprops/action-gh-release@v2
        env:
          GIT_TOKEN: ${{ secrets.DEV_PAT }}
        with:
          draft: true
          files: |
            ./beacond-${{ env.VERSION }}-linux-arm64/beacond-${{ env.VERSION }}-linux-arm64.tar.gz
            ./beacond-${{ env.VERSION }}-linux-amd64/beacond-${{ env.VERSION }}-linux-amd64.tar.gz
            ./beacond-${{ env.VERSION }}-darwin-arm64/beacond-${{ env.VERSION }}-darwin-arm64.tar.gz
          body: |
            $(cat <<- "ENDBODY"
            ![image](https://github.com/berachain/beacon-kit/blob/main/.github/assets/banner.png?raw=true)

            ## Testing Checklist (DELETE ME)

            - [ ] Run on testnet for 1-3 days.
            - [ ] Resync a mainnet node.
            - [ ] Ensure all CI checks pass.

            ## Release Checklist (DELETE ME)

            - [ ] Ensure all crates have had their versions bumped.
            - [ ] Write the summary.
            - [ ] Fill out the update priority.
            - [ ] Ensure all binaries have been added.
            - [ ] Prepare release posts (Twitter, ...).

            ## Summary

            Add a summary, including:

            - Critical bug fixes
            - New features
            - Any breaking changes (and what to expect)

            ## Update Priority

            This table provides priorities for which classes of users should update particular components.

            | User Class           | Priority        |
            |----------------------|-----------------|
            | Payload Builders     | <TODO> |
            | Non-Payload Builders | <TODO>    |

            *See [Update Priorities](https://paradigmxyz.github.io/reth/installation/priorities.html) for more information about this table.*

            ## All Changes

            ${{ steps.changelog.outputs.CHANGELOG }}

            ## Binaries

            [See pre-built binaries documentation.](https://paradigmxyz.github.io/reth/installation/binaries.html)

            The binaries are signed with the PGP key: `A3AE 097C 8909 3A12 4049  DF1F 5391 A3C4 1005 30B4`

            | System | Architecture | Binary | PGP Signature |
            |:---:|:---:|:---:|:---|
            | <img src="https://simpleicons.org/icons/linux.svg" style="width: 32px;"/> | amd64 | [beacond-${{ env.VERSION }}-linux-amd64](https://github.com/${{ env.REPO_NAME }}/releases/download/${{ env.VERSION }}/beacond-${{ env.VERSION }}-amd64-linux.tar.gz) |
            | <img src="https://simpleicons.org/icons/linux.svg" style="width: 32px;"/> | arm64 | [beacond-${{ env.VERSION }}-linux-arm64](https://github.com/${{ env.REPO_NAME }}/releases/download/${{ env.VERSION }}/beacond-${{ env.VERSION }}-arm64-linux.tar.gz) | 
            | <img src="https://simpleicons.org/icons/apple.svg" style="width: 32px;"/> | arm64 | [beacond-${{ env.VERSION }}-darwin-arm64](https://github.com/${{ env.REPO_NAME }}/releases/download/${{ env.VERSION }}/beacond-${{ env.VERSION }}-darwin-arm64.tar.gz) |
            | | | | |
            | **System** | **Option** | - | **Resource** |
            | <img src="https://simpleicons.org/icons/docker.svg" style="width: 32px;"/> | Docker | | [${{ env.IMAGE_NAME }}](https://ghcr.io/berachain/beacon-kit) |
            ENDBODY
            )
            assets=()
            for asset in ./*reth-*.tar.gz*; do
                assets+=("$asset/$asset")
            done
            tag_name="${{ env.VERSION }}"
            echo "$body" | gh release create --draft -t "BeaconKit $tag_name" -F "-" "$tag_name" "${assets[@]}"

